spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_FORMAT_SQL:false}

app:
  cors:
    allowed-origins: ${FRONTEND_ALLOWED_ORIGINS}
  mail:
    enabled: ${APP_MAIL_ENABLED:true}

server:
  servlet:
    session:
      cookie:
        secure: ${SESSION_COOKIE_SECURE:true}
        same-site: ${SESSION_COOKIE_SAME_SITE:none}
